export interface CatalogoObraSocial {
  codigo: string;
  nombre: string;
  sigla: string;
  descripcion: string;
  razonSocial: string;
  domicilio: string | null;
  localidad: string | null;
  tipoContribucion: "INSCRIPTO" | "NO_INSCRIPTO" | "EXENTO" | "MONOTRIBUTO" | "CONSUMIDOR_FINAL";
  tipoIva: "IVA_0" | "IVA_10_5" | "IVA_21";
  cuit: string;
  porcentajeDescMedicamentos: number;
}

/**
 * Catálogo de obras sociales (fuente de verdad del seed y de la BD dev).
 * PAMI / INSSJP / IPS NO forman parte del catálogo.
 * Los CUIT marcados como sintéticos son válidos módulo 11 (solo desarrollo).
 */
export const CATALOGO_OBRAS_SOCIALES: CatalogoObraSocial[] = [
  {
    codigo: "0-0469",
    nombre: "OSDE",
    sigla: "OSDE",
    descripcion: "Medicina prepaga privada — cobertura ambulatoria e internación con cartilla propia",
    razonSocial: "Organización de Servicios Directos Empresarios S.A.",
    domicilio: "Av. Córdoba 1313",
    localidad: "CABA",
    tipoContribucion: "INSCRIPTO",
    tipoIva: "IVA_21",
    cuit: "30-70832227-6",
    porcentajeDescMedicamentos: 0,
  },
  {
    codigo: "0-0300",
    nombre: "Swiss Medical",
    sigla: "SM",
    descripcion: "Medicina prepaga con red propia de sanatorios y laboratorios",
    razonSocial: "Swiss Medical Group S.A.",
    domicilio: "Av. Alicia Moreau de Justo 2050",
    localidad: "CABA",
    tipoContribucion: "INSCRIPTO",
    tipoIva: "IVA_21",
    cuit: "30-65242799-1",
    porcentajeDescMedicamentos: 0,
  },
  {
    codigo: "0-0301",
    nombre: "Galeno",
    sigla: "GALENO",
    descripcion: "Medicina prepaga del Grupo Galeno — cobertura ambulatoria, internación y cartilla amplia",
    razonSocial: "Galeno S.A.",
    domicilio: "Av. Córdoba 950",
    localidad: "CABA",
    tipoContribucion: "INSCRIPTO",
    tipoIva: "IVA_21",
    cuit: "30-70120003-5",
    porcentajeDescMedicamentos: 0,
  },
  {
    codigo: "0-0302",
    nombre: "Medicus",
    sigla: "MEDICUS",
    descripcion: "Medicina prepaga con red de prestadores en todo el país",
    razonSocial: "Medicus S.A. de Asistencia Médica y Científica",
    domicilio: "Av. de Mayo 1370",
    localidad: "CABA",
    tipoContribucion: "INSCRIPTO",
    tipoIva: "IVA_21",
    cuit: "30-70120004-3",
    porcentajeDescMedicamentos: 0,
  },
  {
    codigo: "0-0303",
    nombre: "Omint",
    sigla: "OMINT",
    descripcion: "Medicina prepaga con planes por franjas etarias y red propia",
    razonSocial: "OMINT Sociedad Anónima de Servicios",
    domicilio: "Av. del Libertador 602",
    localidad: "CABA",
    tipoContribucion: "INSCRIPTO",
    tipoIva: "IVA_21",
    cuit: "30-70120005-1",
    porcentajeDescMedicamentos: 0,
  },
  {
    codigo: "0-0304",
    nombre: "Accord Salud",
    sigla: "ACCORD",
    descripcion: "Medicina prepaga del Grupo Sancor Seguros — cobertura nacional",
    razonSocial: "Accord Salud S.A.",
    domicilio: "Bv. Oroño 1510",
    localidad: "Rosario",
    tipoContribucion: "INSCRIPTO",
    tipoIva: "IVA_21",
    cuit: "30-70120006-9",
    porcentajeDescMedicamentos: 0,
  },
  {
    codigo: "0-0305",
    nombre: "Sancor Salud",
    sigla: "SANCOR",
    descripcion: "Medicina prepaga del Grupo Sancor Seguros — cobertura nacional",
    razonSocial: "Sancor Salud S.A.",
    domicilio: "Av. Independencia 1122",
    localidad: "Sunchales",
    tipoContribucion: "INSCRIPTO",
    tipoIva: "IVA_21",
    cuit: "30-70120007-8",
    porcentajeDescMedicamentos: 0,
  },
  {
    codigo: "0-0306",
    nombre: "Prevención Salud",
    sigla: "PREVENCION",
    descripcion: "Medicina prepaga con cobertura ambulatoria, internación y programas preventivos",
    razonSocial: "Prevención Salud S.A.",
    domicilio: "Av. Pueyrredón 510",
    localidad: "CABA",
    tipoContribucion: "INSCRIPTO",
    tipoIva: "IVA_21",
    cuit: "30-70120008-6",
    porcentajeDescMedicamentos: 0,
  },
  {
    codigo: "0-0307",
    nombre: "William Hope",
    sigla: "WH",
    descripcion: "Mutual de servicios de salud con cobertura en el NOA (Jujuy)",
    razonSocial: "William Hope",
    domicilio: "Av. Almirante Brown 1250",
    localidad: "San Salvador de Jujuy",
    tipoContribucion: "INSCRIPTO",
    tipoIva: "IVA_0",
    cuit: "30-70120009-4",
    porcentajeDescMedicamentos: 10,
  },
  {
    codigo: "0-0120",
    nombre: "IOMA",
    sigla: "IOMA",
    descripcion: "Instituto de Obra Médico Asistencial — obra social provincial bonaerense",
    razonSocial: "Instituto de Obra Médico Asistencial de la Provincia de Buenos Aires",
    domicilio: "Calle 5 N° 989",
    localidad: "La Plata",
    tipoContribucion: "INSCRIPTO",
    tipoIva: "IVA_0",
    cuit: "33-66400001-1",
    porcentajeDescMedicamentos: 40,
  },
  {
    codigo: "0-0310",
    nombre: "OSECAC",
    sigla: "OSECAC",
    descripcion: "Obra social sindical del personal de comercio — cobertura nacional",
    razonSocial: "Obra Social de Empleados de Comercio y Actividades Civiles (OSECAC)",
    domicilio: "Av. Belgrano 1710",
    localidad: "CABA",
    tipoContribucion: "INSCRIPTO",
    tipoIva: "IVA_0",
    cuit: "33-70120010-8",
    porcentajeDescMedicamentos: 30,
  },
  {
    codigo: "0-0311",
    nombre: "OSPE",
    sigla: "OSPE",
    descripcion: "Obra social del personal de la actividad petrolera y energética",
    razonSocial: "Obra Social del Personal Petrolero (OSPE)",
    domicilio: "Gral. San Martín 2450",
    localidad: "Neuquén",
    tipoContribucion: "INSCRIPTO",
    tipoIva: "IVA_0",
    cuit: "33-70120011-6",
    porcentajeDescMedicamentos: 20,
  },
  {
    codigo: "0-0312",
    nombre: "OSPECON",
    sigla: "OSPECON",
    descripcion: "Obra social del personal de la construcción (Construir Salud)",
    razonSocial: "OSPECON — Obra Social del Personal de la Construcción",
    domicilio: "Av. Paseo Colón 823",
    localidad: "CABA",
    tipoContribucion: "INSCRIPTO",
    tipoIva: "IVA_0",
    cuit: "33-70120012-4",
    porcentajeDescMedicamentos: 25,
  },
  {
    codigo: "0-0313",
    nombre: "OSPEDYC",
    sigla: "OSPEDYC",
    descripcion: "Obra social del personal de entidades deportivas y civiles (UTEDYC)",
    razonSocial: "OSPEDYC — Obra Social del Personal de Entidades Deportivas y Civiles",
    domicilio: "Av. de Mayo 1370",
    localidad: "CABA",
    tipoContribucion: "INSCRIPTO",
    tipoIva: "IVA_0",
    cuit: "33-70120013-2",
    porcentajeDescMedicamentos: 20,
  },
  {
    codigo: "0-0314",
    nombre: "OSDEPYM",
    sigla: "OSDEPYM",
    descripcion: "Obra social de empresarios, profesionales y monotributistas",
    razonSocial: "OSDEPYM — Obra Social de Empresarios, Profesionales y Monotributistas",
    domicilio: "Reconquista 458",
    localidad: "CABA",
    tipoContribucion: "INSCRIPTO",
    tipoIva: "IVA_0",
    cuit: "33-70120014-0",
    porcentajeDescMedicamentos: 30,
  },
  {
    codigo: "0-0315",
    nombre: "Unión Personal",
    sigla: "UP",
    descripcion: "Obra social del personal de dirección de empresas y afines",
    razonSocial: "Unión Personal — Obra Social",
    domicilio: "Av. Corrientes 1144",
    localidad: "CABA",
    tipoContribucion: "INSCRIPTO",
    tipoIva: "IVA_0",
    cuit: "33-70120015-9",
    porcentajeDescMedicamentos: 20,
  },
  {
    codigo: "0-0316",
    nombre: "Luis Pasteur",
    sigla: "PASTEUR",
    descripcion: "Mutual de salud con red de prestadores y programas de medicina preventiva",
    razonSocial: "Obra Social Luis Pasteur",
    domicilio: "Av. Santa Fe 1060",
    localidad: "CABA",
    tipoContribucion: "INSCRIPTO",
    tipoIva: "IVA_0",
    cuit: "33-70120016-7",
    porcentajeDescMedicamentos: 10,
  },
  {
    codigo: "0-0317",
    nombre: "Jerárquicos Salud",
    sigla: "JERARQUICOS",
    descripcion: "Obra social del personal jerárquico — cobertura nacional",
    razonSocial: "Jerárquicos Salud — Obra Social del Personal Jerárquico",
    domicilio: "Av. Córdoba 1234",
    localidad: "CABA",
    tipoContribucion: "INSCRIPTO",
    tipoIva: "IVA_0",
    cuit: "33-70120017-5",
    porcentajeDescMedicamentos: 20,
  },
  {
    codigo: "0-0318",
    nombre: "OSDOP",
    sigla: "OSDOP",
    descripcion: "Obra social de docentes de establecimientos educativos privados",
    razonSocial: "OSDOP — Obra Social de Docentes Particulares",
    domicilio: "Lavalle 1290",
    localidad: "CABA",
    tipoContribucion: "INSCRIPTO",
    tipoIva: "IVA_0",
    cuit: "33-70120018-3",
    porcentajeDescMedicamentos: 30,
  },
  {
    codigo: "0-0319",
    nombre: "OSPAT",
    sigla: "OSPAT",
    descripcion: "Obra social del personal de la actividad hípica y del turf",
    razonSocial: "OSPAT — Obra Social del Personal de la Actividad del Turf",
    domicilio: "Av. del Libertador 4200",
    localidad: "CABA",
    tipoContribucion: "INSCRIPTO",
    tipoIva: "IVA_0",
    cuit: "33-70120019-1",
    porcentajeDescMedicamentos: 20,
  },
  {
    codigo: "0-0320",
    nombre: "OSCHOCA",
    sigla: "OSCHOCA",
    descripcion: "Obra social de los trabajadores de la industria de la construcción (UOCRA)",
    razonSocial: "OSCHOCA — Obra Social del Personal de la Construcción",
    domicilio: "Av. Belgrano 1210",
    localidad: "CABA",
    tipoContribucion: "INSCRIPTO",
    tipoIva: "IVA_0",
    cuit: "33-70120020-5",
    porcentajeDescMedicamentos: 30,
  },
  {
    codigo: "0-0321",
    nombre: "OSPEPRI",
    sigla: "OSPEPRI",
    descripcion: "Obra social del personal de la pequeña y mediana empresa (CAME)",
    razonSocial: "OSPEPRI — Obra Social del Personal de la Pequeña y Mediana Empresa",
    domicilio: "Av. Rivadavia 1255",
    localidad: "CABA",
    tipoContribucion: "INSCRIPTO",
    tipoIva: "IVA_0",
    cuit: "33-70120021-3",
    porcentajeDescMedicamentos: 20,
  },
  {
    codigo: "0-0322",
    nombre: "DASUTEN",
    sigla: "DASUTEN",
    descripcion: "Obra social de docentes y no docentes de la Universidad Tecnológica Nacional",
    razonSocial: "D.A.S.U.Te.N. — Dirección de Acción Social de la Universidad Tecnológica Nacional",
    domicilio: "11 de Abril 461",
    localidad: "Bahía Blanca",
    tipoContribucion: "INSCRIPTO",
    tipoIva: "IVA_0",
    cuit: "33-70120022-1",
    porcentajeDescMedicamentos: 25,
  },
  {
    codigo: "0-0323",
    nombre: "IOSFA",
    sigla: "IOSFA",
    descripcion: "Obra social de las Fuerzas Armadas — cobertura nacional",
    razonSocial: "IOSFA — Instituto de Obra Social de las Fuerzas Armadas",
    domicilio: "Av. Corrientes 2093",
    localidad: "CABA",
    tipoContribucion: "INSCRIPTO",
    tipoIva: "IVA_0",
    cuit: "33-70120023-9",
    porcentajeDescMedicamentos: 20,
  },
  {
    codigo: "0-0324",
    nombre: "APSOT",
    sigla: "APSOT",
    descripcion: "Obra social del personal superior de la Organización Techint",
    razonSocial: "APSOT — Asociación del Personal Superior de la Organización Techint",
    domicilio: "Della Paolera 299",
    localidad: "CABA",
    tipoContribucion: "INSCRIPTO",
    tipoIva: "IVA_0",
    cuit: "33-70120024-8",
    porcentajeDescMedicamentos: 15,
  },
  {
    codigo: "0-9999",
    nombre: "Particular",
    sigla: "PARTICULAR",
    descripcion: "Paciente particular — pago directo sin obra social",
    razonSocial: "Paciente particular",
    domicilio: null,
    localidad: null,
    tipoContribucion: "CONSUMIDOR_FINAL",
    tipoIva: "IVA_21",
    cuit: "30-70120025-6",
    porcentajeDescMedicamentos: 0,
  },
];